# Generated by Django 3.0.7 on 2020-06-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Başlık Bilgisi Girilir', max_length=50, null=True, verbose_name='Başlık')),
                ('content', models.TextField(help_text='Oluşturmak İstediğiniz Spotu Giriniz', max_length=2000, null=True, verbose_name='Spot Bilgi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Spotlar',
                'ordering': ['-created_date'],
            },
        ),
    ]
