# Generated by Django 3.0.7 on 2020-06-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
