# Generated by Django 3.0.7 on 2020-06-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200611_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=10, verbose_name='Kategori İsim')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
    ]
