# Generated by Django 3.0.7 on 2020-06-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_kategoriler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='kategoriler',
            field=models.ManyToManyField(null=True, related_name='article', to='article.Category'),
        ),
    ]
