# Generated by Django 3.0.7 on 2020-06-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='kategoriler',
            field=models.ManyToManyField(related_name='article', to='article.Category'),
        ),
    ]
