# Generated by Django 3.0.7 on 2020-06-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200612_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=2000, null=True, verbose_name='Spot Bilgi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default/61733.png', help_text='Resim Yükleyebilirsiniz', null=True, upload_to='', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Başlık'),
        ),
    ]
