# Generated by Django 3.0.7 on 2020-06-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200612_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default/61733.png', help_text='Resim Yükleyebilirsiniz', null=True, upload_to='resimler', verbose_name='Resim'),
        ),
    ]
