# Generated by Django 3.0.7 on 2020-06-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200612_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
