# Generated by Django 3.0.7 on 2020-06-12 11:13

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20200612_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default/61733.png', help_text='Resim Yükleyebilirsiniz', null=True, upload_to=article.models.upload_to, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='article',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
