# Generated by Django 3.0.7 on 2020-06-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20200612_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='yayin_taslak',
            field=models.CharField(choices=[('yayin', 'YAYIN'), ('taslak', 'TASLAK')], default='yayin', max_length=6),
        ),
    ]
