# Generated by Django 3.0.7 on 2020-06-14 07:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20200612_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=2000, null=True, verbose_name='Spot Bilgi'),
        ),
    ]
