# Generated by Django 3.0.7 on 2020-06-14 16:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20200614_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author_firstname', models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim')),
                ('comment_author_lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soy İsim')),
                ('comment_author_email', models.EmailField(help_text='Doldurmanız Gerekiyor', max_length=254, null=True, verbose_name='E-Mail')),
                ('comment_content', ckeditor.fields.RichTextField(help_text='Yorumunuzu Giriniz', max_length=2000, null=True, verbose_name='Yorum')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Yorum Tarihi')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.Article', verbose_name='Spot')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
