# Generated by Django 3.0.7 on 2020-06-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date'], 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yorum Tarihi'),
        ),
    ]
