# Generated by Django 3.0.7 on 2020-06-27 20:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_auto_20200623_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritearticle',
            options={'verbose_name_plural': 'Favori İçerikler'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=10000, null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_article', to='article.Article', verbose_name='Favori İçerik'),
        ),
    ]
