# Generated by Django 3.0.7 on 2020-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(None, 'Tercihiniz'), ('diger', 'DİĞER'), ('erkek', 'ERKEK'), ('kadın', 'KADIN')], max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
    ]
