# Generated by Django 3.0.7 on 2020-06-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='following',
            options={'verbose_name_plural': 'Takipleşme Sistemi'},
        ),
    ]
